site: Colorie
url: 
author: Colorie
author:
  name: Colorie
  email: 
  url: 
  avatar: 
title: Distance Over Time
description: Colorie - Single column blog and portfolio Jekyll theme 
logo: 
image: 
twitter: ronaldsvilcins  
twitter:
  username: ronaldsvilcins
  creator: ronaldsvilcins
  card: summary
social:
  name: Ronalds Vilcins
  links:
    - https://twitter.com/#
    - https://www.dribbble.com/#
    - https://github.com/#
    - https://codepen.io/#
  
permalink: pretty

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /projects/:slug

social_media_icons:
  GitHub: '/assets/images/sm/square-github.svg'
  Itch.io: '/assets/images/sm/itch-io.svg'
  LinkedIn: '/assets/images/sm/linkedin.svg'
  Twitter: '/assets/images/sm/square-x-twitter.svg'


role_icons:
  Accessibility: '/assets/images/roles/access.svg'
  Artist: '/assets/images/roles/art.svg'
  Audio: '/assets/images/roles/audio.svg'
  Designer: '/assets/images/roles/design.svg'
  Producer: '/assets/images/roles/producer.svg'
  Programmer: '/assets/images/roles/programmer.svg'
  QA: '/assets/images/roles/qa.svg'
  Writer: '/assets/images/roles/writer.svg'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
