site: Distance Over Time
url: 
author: Distance Over Time Studios
author:
  name: Distance Over Time Studios
  email: 
  url: 
  avatar: 
title: DOTs
description: Distance Over Time Studios - Career switchers making accessible games
logo: 
image:
  
permalink: pretty

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /projects/:slug

social_media_icons:
  Bluesky: '/assets/images/sm/bluesky.svg'
  GitHub: '/assets/images/sm/github.svg'
  Instagram: '/assets/images/sm/instagram.svg'
  Itch.io: '/assets/images/sm/itch-io.svg'
  LinkedIn: '/assets/images/sm/linkedin.svg'
  Mastodon: '/assets/images/sm/mastodon.svg'
  TikTok: '/assets/images/sm/tiktok.svg'
  Twitch: '/assets/images/sm/twitch.svg'
  Twitter: '/assets/images/sm/twitter-x.svg'
  YouTube: '/assets/images/sm/youtube.svg'


role_icons:
  Accessibility: '/assets/images/roles/access.svg'
  Artist: '/assets/images/roles/art.svg'
  Audio: '/assets/images/roles/audio.svg'
  Game Designer: '/assets/images/roles/design.svg'
  UX/UI Designer: '/assets/images/roles/design2.svg'
  Producer: '/assets/images/roles/producer.svg'
  Programmer: '/assets/images/roles/programmer.svg'
  QA: '/assets/images/roles/qa.svg'
  Writer: '/assets/images/roles/writer.svg'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
