site: Colorie
url: 
author: Colorie
author:
  name: Colorie
  email: 
  url: 
  avatar: 
title: Colorie
description: Colorie - Single column blog and portfolio Jekyll theme 
logo: 
image: 
twitter: ronaldsvilcins  
twitter:
  username: ronaldsvilcins
  creator: ronaldsvilcins
  card: summary
social:
  name: Ronalds Vilcins
  links:
    - https://twitter.com/#
    - https://www.dribbble.com/#
    - https://github.com/#
    - https://codepen.io/#
  
permalink: pretty

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug

social_media_icons:
  Twitter: '/assets/images/twitter.png'
  LinkedIn: '/assets/images/linkedin.png'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
